version: '3.9'

services:
  springboot:
    build:
      context: ./backend/culturefit
    ports:
      - "9000:9000"
    volumes:
      - ./backend/culturefit/uploads:/app/uploads
    environment:
      SERVER_PORT: ${SERVER_PORT}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}

      MAIL_PASS: ${MAIL_PASS}
      JWT_SECRET_CONFIRMATION: ${JWT_SECRET_CONFIRMATION}

      JWT_SECRET: ${JWT_SECRET}

      DIRECTORY_EXERCISE_IMAGES: ${DIRECTORY_EXERCISE_IMAGES}
      DIRECTORY_PROFILE_IMAGES: ${DIRECTORY_PROFILE_IMAGES}
      DIRECTORY_LESSON_VIDEOS: ${DIRECTORY_LESSON_VIDEOS}
      DIRECTORY_LESSON_THUMBNAILS: ${DIRECTORY_LESSON_THUMBNAILS}

      API_URL_FRONT: ${API_URL_FRONT}

    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: culturefit-bd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
